version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development